# Generated by Django 3.1.5 on 2021-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=20)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_user', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('item_content', models.TextField(help_text='Enter item content')),
                ('item_amount', models.IntegerField()),
                ('item_watermark', models.BooleanField()),
            ],
        ),
    ]
