# Generated by Django 3.1.5 on 2021-02-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210204_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_user',
        ),
    ]
