# Generated by Django 3.1.5 on 2021-02-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckMacValue', models.TextField()),
                ('CustomField1', models.TextField()),
                ('CustomField2', models.TextField()),
                ('CustomField3', models.TextField()),
                ('CustomField4', models.TextField()),
                ('MerchantID', models.TextField()),
                ('MerchantTradeNo', models.TextField()),
                ('PaymentDate', models.DateTimeField()),
                ('PaymentType', models.TextField()),
                ('PaymentTypeChargeFee', models.TextField()),
                ('RtnCode', models.TextField()),
                ('RtnMsg', models.TextField()),
                ('SimulatePaid', models.TextField()),
                ('StoreID', models.TextField()),
                ('TradeAmt', models.TextField()),
                ('TradeDate', models.DateTimeField()),
                ('TradeNo', models.TextField()),
            ],
        ),
    ]
