# Generated by Django 3.1.6 on 2021-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaymentDate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='TradeDate',
            field=models.TextField(),
        ),
    ]
