# Generated by Django 3.1.5 on 2021-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210207_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_HashIV',
            field=models.CharField(default='v77hoKGq4kWxNNIS', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_HashKey',
            field=models.CharField(default='5294y06JbISpM5x9', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_MerchantID',
            field=models.CharField(default='2000132', max_length=20),
        ),
    ]
